# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import embeddings_pb2 as embeddings__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in embeddings_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbeddingsStub(object):
    """Embeddings service - generates vector embeddings for text content
    Creates and stores Chunk nodes in FalkorDB with embeddings
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Embed = channel.unary_unary(
                '/confuse.embeddings.v1.Embeddings/Embed',
                request_serializer=embeddings__pb2.EmbedRequest.SerializeToString,
                response_deserializer=embeddings__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.BatchEmbed = channel.unary_unary(
                '/confuse.embeddings.v1.Embeddings/BatchEmbed',
                request_serializer=embeddings__pb2.BatchEmbedRequest.SerializeToString,
                response_deserializer=embeddings__pb2.BatchEmbedResponse.FromString,
                _registered_method=True)
        self.ProcessAndStoreChunks = channel.unary_unary(
                '/confuse.embeddings.v1.Embeddings/ProcessAndStoreChunks',
                request_serializer=embeddings__pb2.ProcessChunksRequest.SerializeToString,
                response_deserializer=embeddings__pb2.ProcessChunksResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/confuse.embeddings.v1.Embeddings/GetModelInfo',
                request_serializer=embeddings__pb2.ModelInfoRequest.SerializeToString,
                response_deserializer=embeddings__pb2.ModelInfo.FromString,
                _registered_method=True)


class EmbeddingsServicer(object):
    """Embeddings service - generates vector embeddings for text content
    Creates and stores Chunk nodes in FalkorDB with embeddings
    """

    def Embed(self, request, context):
        """Single embedding generation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchEmbed(self, request, context):
        """Batch embedding generation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessAndStoreChunks(self, request, context):
        """Process chunks and store in FalkorDB as Chunk nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Model information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=embeddings__pb2.EmbedRequest.FromString,
                    response_serializer=embeddings__pb2.EmbedResponse.SerializeToString,
            ),
            'BatchEmbed': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchEmbed,
                    request_deserializer=embeddings__pb2.BatchEmbedRequest.FromString,
                    response_serializer=embeddings__pb2.BatchEmbedResponse.SerializeToString,
            ),
            'ProcessAndStoreChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessAndStoreChunks,
                    request_deserializer=embeddings__pb2.ProcessChunksRequest.FromString,
                    response_serializer=embeddings__pb2.ProcessChunksResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=embeddings__pb2.ModelInfoRequest.FromString,
                    response_serializer=embeddings__pb2.ModelInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'confuse.embeddings.v1.Embeddings', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('confuse.embeddings.v1.Embeddings', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Embeddings(object):
    """Embeddings service - generates vector embeddings for text content
    Creates and stores Chunk nodes in FalkorDB with embeddings
    """

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/confuse.embeddings.v1.Embeddings/Embed',
            embeddings__pb2.EmbedRequest.SerializeToString,
            embeddings__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchEmbed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/confuse.embeddings.v1.Embeddings/BatchEmbed',
            embeddings__pb2.BatchEmbedRequest.SerializeToString,
            embeddings__pb2.BatchEmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessAndStoreChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/confuse.embeddings.v1.Embeddings/ProcessAndStoreChunks',
            embeddings__pb2.ProcessChunksRequest.SerializeToString,
            embeddings__pb2.ProcessChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/confuse.embeddings.v1.Embeddings/GetModelInfo',
            embeddings__pb2.ModelInfoRequest.SerializeToString,
            embeddings__pb2.ModelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
